version: '3'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres_container
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my_network
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    networks:
      - my_network
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: